/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: msg.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "msg.pb-c.h"
void   client__init
                     (Client         *message)
{
  static const Client init_value = CLIENT__INIT;
  *message = init_value;
}
size_t client__get_packed_size
                     (const Client *message)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t client__pack
                     (const Client *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t client__pack_to_buffer
                     (const Client *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &client__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Client *
       client__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Client *)
     protobuf_c_message_unpack (&client__descriptor,
                                allocator, len, data);
}
void   client__free_unpacked
                     (Client *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &client__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor client__field_descriptors[1] =
{
  {
    "ch",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(Client, ch),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned client__field_indices_by_name[] = {
  0,   /* field[0] = ch */
};
static const ProtobufCIntRange client__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor client__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "client",
  "Client",
  "Client",
  "",
  sizeof(Client),
  1,
  client__field_descriptors,
  client__field_indices_by_name,
  1,  client__number_ranges,
  (ProtobufCMessageInit) client__init,
  NULL,NULL,NULL    /* reserved[123] */
};
